---
# tasks file for roles/launch_proxy
- name: Run HTTPD launch_proxy
  docker_container:
    name: proxy
    image: eduardo9703/proxy:latest
    ports:
      - "80:80"
    networks:
      - name: my_network