---
# tasks file for roles/launch_database
- name: Remove old database container
  docker_container:
    name: database
    state: absent

- name: Run database container
  docker_container:
    name: Database
    image: eduardo9703/database:latest
    pull: true
    env:
      POSTGRES_USER: usr
      POSTGRES_PASSWORD: pwd
      POSTGRES_DB: database
    
    networks:
      - name: my_network

    ports:
      - "4000:5432"