version: '3.8'

services:
  backend:
    build:
      context: ./backend/simpleapi
    networks:
      - app-network
    depends_on:
      - database

  database:
    build:
      context: ./database
    networks:
      - app-network
    volumes:
      - pgdata:/var/lib/postgresql/data

  httpd:
    build:
      context: ./http
    ports:
      - "8082:80"
    networks:
      - app-network
    depends_on:
      - backend

networks:
  app-network:

volumes:
  pgdata:
