- hosts: all
  gather_facts: true
  become: true

  tasks:
    - name: Test connection
      ping:
    - name: Install required packages
      apt:
          name:
            - apt-transport-https
            - ca-certificates
            - curl
            - gnupg
            - lsb-release
          state: present
          update_cache: yes
    - name: Add Docker’s GPG key
      apt_key:
        url: https://download.docker.com/linux/debian/gpg
        state: present

    - name: Add Docker APT repository
      apt_repository:
        repo: "deb [arch=amd64] https://download.docker.com/linux/debian {{ ansible_distribution_release }} stable"
        state: present
        update_cache: yes

    - name: Install Docker
      apt:
        name: docker-ce
        state: present

    - name: Install Python and pip3
      apt:
        name:
          - python3
          - python3-pip
        state: present
        
    - name: Ensure python3-venv is installed
      apt:
        name: python3.11-venv
        state: present
      become: true

    - name: Create a virtual environment for Docker SDK
      command: python3 -m venv /opt/docker_venv

    - name: Install Docker SDK for Python
      command: /opt/docker_venv/bin/pip install docker

    - name: Ensure Docker is running
      service:
        name: docker
        state: started 