all:
 vars:
   ansible_user: admin
   ansible_python_interpreter: /usr/bin/python3
   ansible_ssh_private_key_file: ~/.ssh/id_rsa
 children:
   prod:
     hosts: eduardoantonio.polancoarrindell.takima.cloud
