name: Build and push docker image

on:
  push:
    branches:
      - main

jobs:
  build-and-test-backend:
    runs-on: ubuntu-24.04

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Log in to DockerHub
        run: echo "${{ secrets.DOCKERHUB_TOKEN }}" | docker login -u "${{ secrets.DOCKERHUB_USERNAME }}" --password-stdin

      # BACKEND
      - name: Build and push backend
        uses: docker/build-push-action@v5
        with:
          context: ./TP/backend/simpleapi
          push: true
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/tp-devops-simple-api:latest

      # DATABASE
      - name: Build and push database
        uses: docker/build-push-action@v5
        with:
          context: ./TP/database
          push: true
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/tp-devops-database:latest

      # HTTPD
      - name: Build and push httpd
        uses: docker/build-push-action@v5
        with:
          context: ./TP/http
          push: true
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/tp-devops-httpd:latest
