name: CI devops 2025

on:
  push:
    branches: [main] #TODO
  pull_request:

jobs:
  test-backend:
    runs-on: ubuntu-24.04
    steps:
      - name: Checkout your GitHub code
      #checkout your github code using actions/checkout@v4
        uses: actions/checkout@v4
      #do the same with another action (actions/setup-java@v4) that enable to setup jdk 21
      - name: Set up JDK 21
      #TODO
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'temurin'
      #finally build your app with the latest command
      - name: Build and test with Maven
        run: cd TP/backend/simpleapi && mvn clean verify
      - name: SonarCloud Analysis
        run: cd TP/backend/simpleapi && mvn verify sonar:sonar -Dsonar.projectKey=eduardopolanc -Dsonar.organization=eduardopolanc -Dsonar.token=${{ secrets.SONAR_TOKEN }}
